name: black_hole_flutter
description: A package absorbing all Flutter utility functions, including extension functions and commonly used widgets
version: 1.1.0
repository: https://github.com/JonasWanke/black_hole_flutter
screenshots:
  - description: Fancy buttons feature a loading state
    path: doc/widgets-buttons.gif

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 6da7cfcf12aa2755ed9f7e1a59458c600ef3e1d0
